services:
  app:
    image: ghcr.io/axsddlr/jobapptracker:0.2
    container_name: "job_app_tracker"
    volumes:
      - sqlite_data:/usr/src/app/data
    ports:
      - "3110:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - SQLITE_PATH=/usr/src/app/data/jobapp.db
    restart: unless-stopped

volumes:
  sqlite_data:
